# Generated by Django 6.0.3 on 2026-03-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfq', '0002_alter_rfq_options_rfq_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
