# Generated by Django 6.0.3 on 2026-03-12 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imo_number', models.CharField(max_length=10, unique=True)),
                ('vessel_type', models.CharField(choices=[('bulk_carrier', 'Bulk Carrier'), ('tanker', 'Tanker'), ('container', 'Container'), ('passenger', 'Passenger')], max_length=20)),
                ('flag_state', models.CharField(max_length=20)),
                ('year_build', models.IntegerField()),
                ('gross_tonnage', models.IntegerField()),
                ('classification_society', models.CharField(max_length=20)),
                ('operational_status', models.CharField(default='in_service', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
