# Generated by Django 6.0.3 on 2026-03-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name_plural': 'Purchase Orders'},
        ),
    ]
