# Generated by Django 6.0.3 on 2026-03-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0002_alter_purchaseorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
